// СГЕНЕРИРОВАНО tools/v2/gen_schemas.py из docs/tz/v2/СХЕМЫ-ПОЛЕЙ-V2.yaml — руками не править
//
// Перечень видов v2 — единственный законный источник для кода: вид, которого
// здесь нет, не существует (ТЗ-BACKEND §2.6). Слой и сцена рождения нужны
// сторожам: видимость по сцене и запрет зависимостей вверх по слоям.
package orbita.kernel.schema

/** Слой модели данных: L0 — полки, L5 — выпуск. */
enum class Layer { L0, L1, L2, L3, L4, L5 }

/**
 * Вид сущности v2.
 *
 * @property code машинный код вида — им же названа схема в schemas/v2
 * @property title имя вида по-русски: интерфейс показывает его, не код
 * @property layer слой; зависимости идут только вниз
 * @property bornIn сцена рождения; null — сущность полки, у неё сцены нет
 * @property statusModel статусная модель, если у вида она есть
 */
data class KindSpec(
    val code: String,
    val title: String,
    val layer: Layer,
    val bornIn: String?,
    val statusModel: String?,
    val requiredFields: List<String>,
    /** Все поля вида по истине YAML — правка на месте отбивает поле вне схемы (З-03). */
    val fields: List<String> = emptyList(),
    /**
     * Поля, которые по истине схем суть ОДНА ссылка на факт (`ref fact`).
     * Их подставляет система: основание сущности она знает сама. Поля с
     * составным источником (перечень ссылок у требования, файл у задания
     * разбора) сюда не входят — туда код факта писать нельзя.
     */
    val factRefFields: List<String> = emptyList(),
    /**
     * Перечни вида по истине схем: поле → допустимые значения.
     * Ими проверяется ввод и ответ службы; девятой копии перечня в
     * коде быть не должно — она разойдётся с истиной молча.
     */
    val enums: Map<String, List<String>> = emptyMap(),
    /**
     * Поля-величины вида: им значение и единица приходят ПАРОЙ
     * («measure{op,value|min,max,unit→unit}»), а не двумя плоскими
     * полями. Имя поля знает истина схем — не код, который пару кладёт.
     */
    val measures: List<String> = emptyList(),
    /**
     * Русское имя поля (`label` истины схем). Экран показывает ТОЛЬКО
     * его: код поля на экране запрещён правилом владельца
     * (`field_rules.label`, 18.09) — человек не обязан знать наши коды.
     */
    val labels: Map<String, String> = emptyMap(),
    /**
     * Стадия, к которой поле обязано быть заполнено (`required_at`):
     * `accept` — при приёме предложения, `baseline` — к базированию,
     * `SRR` и прочие — к точке. Суффиксы говорят, кто и чем заполняет:
     * `system` · `default(x)` · `from_basis` · `auto` · `tbd_allowed` ·
     * `proposed`. Форма приёма спрашивает ровно то, что названо `accept`
     * и не подставляется само (журнал ПМИ-7, З-09).
     */
    val requiredAt: Map<String, String> = emptyMap(),
    /**
     * Примечание поля словами истины: «обязателен для performance» у
     * показателя, «TBD допустим до SRR» у метода. Экран показывает его
     * рядом с полем — иначе необязательное поле выглядит долгом.
     */
    val notes: Map<String, String> = emptyMap(),
)

object GeneratedKinds {

    val all: List<KindSpec> = listOf(
        KindSpec("unit", "единица измерения", Layer.L0, null, null, listOf("dimension", "symbol", "name", "canonical", "conversion_type"), listOf("dimension", "symbol", "name", "canonical", "factor", "conversion_type", "offset", "rate_date", "display_default"), listOf(), mapOf("conversion_type" to listOf("linear", "offset", "log", "rate")), listOf(), mapOf("dimension" to "Размерность", "symbol" to "Символ", "name" to "Наименование", "canonical" to "Каноническое имя", "factor" to "Множитель", "conversion_type" to "Тип преобразования", "offset" to "Смещение", "rate_date" to "Дата курса", "display_default" to "Показывать по умолчанию"), emptyMap(), mapOf("factor" to "обязателен, если не канон", "rate_date" to "для валют")),
        KindSpec("glossary_term", "термин глоссария", Layer.L0, null, null, listOf("term_ru", "definition"), listOf("term_ru", "term_en", "definition", "source", "doc_type_brief", "default_take_to_prompt"), listOf(), emptyMap(), listOf(), mapOf("term_ru" to "Термин (рус.)", "term_en" to "Термин (англ.)", "definition" to "Определение", "source" to "Источник", "doc_type_brief" to "Тип документа", "default_take_to_prompt" to "В промпт по умолчанию"), emptyMap(), mapOf("doc_type_brief" to "для типов документов", "default_take_to_prompt" to "умолчание «в промпт» типа")),
        KindSpec("qos_class", "класс обслуживания", Layer.L0, null, null, listOf("code", "name", "latency_max", "guarantee"), listOf("code", "name", "latency_max", "guarantee"), listOf(), mapOf("code" to listOf("A′", "B′", "C′")), listOf("latency_max"), mapOf("code" to "Код", "name" to "Наименование", "latency_max" to "Макс. задержка", "guarantee" to "Гарантия"), emptyMap(), emptyMap()),
        KindSpec("method_catalog", "справочник методов и шкал", Layer.L0, null, null, listOf("catalog", "items"), listOf("catalog", "items"), listOf(), mapOf("catalog" to listOf("verification_method", "trl_scale", "risk_probability", "risk_impact", "status_model", "priority")), listOf(), mapOf("catalog" to "Каталог", "items" to "Элементы"), emptyMap(), emptyMap()),
        KindSpec("normative_document", "норматив с редакцией", Layer.L0, null, null, listOf("designation", "title", "edition", "edition_date"), listOf("designation", "title", "edition", "edition_date", "valid_until", "clauses", "source_mark"), listOf(), mapOf("clauses.applies_to" to listOf("node", "interface", "scene]["), "source_mark" to listOf("И", "В", "П")), listOf(), mapOf("designation" to "Обозначение", "title" to "Заголовок", "edition" to "Редакция", "edition_date" to "Дата редакции", "valid_until" to "Срок действия", "clauses" to "Пункты", "source_mark" to "Метка источника"), emptyMap(), mapOf("clauses" to "порог нормы — поле limit, не число из текста; «Б1: увод ≤ 5 лет» → limit{key:active_lifetime,op:le,value:5,unit:год}")),
        KindSpec("mission_class", "класс миссии", Layer.L0, null, null, listOf("code", "name", "recommended_shelves", "mandatory_models", "default_constraints"), listOf("code", "name", "recommended_shelves", "mandatory_models", "default_constraints", "prompt_context"), listOf(), emptyMap(), listOf(), mapOf("code" to "Код", "name" to "Наименование", "recommended_shelves" to "Рекомендованные полки", "mandatory_models" to "Обязательные модели", "default_constraints" to "Ограничения по умолчанию", "prompt_context" to "Контекст промпта"), emptyMap(), emptyMap()),
        KindSpec("phase_template", "шаблон фазы", Layer.L0, null, null, listOf("standard", "phase", "correspondence", "roles", "scenes", "points", "stage_output_dataset"), listOf("standard", "phase", "correspondence", "roles", "scenes", "points", "stage_output_dataset"), listOf(), mapOf("standard" to listOf("NASA-7120", "RK-11KT", "ISO-15288"), "scenes.track" to listOf("design", "modeling", "management"), "scenes.instantiate_per" to listOf("project", "segment", "element"), "scenes.output" to listOf("kind", "document_template*,maturity*"), "scenes.links.type" to listOf("FS", "SS", "FF", "INPUT"), "stage_output_dataset.baseline_kind" to listOf("functional", "allocated", "product")), listOf(), mapOf("standard" to "Стандарт", "phase" to "Фаза", "correspondence" to "Соответствия", "roles" to "Роли", "scenes" to "Сцены", "points" to "Точки", "stage_output_dataset" to "Исходные данные стадии"), emptyMap(), mapOf("phase" to "ключ фазы в стандарте", "correspondence" to "карта соответствий стадий", "roles" to "задействованный персонал стадии", "scenes" to "дорожки и экземпляры на узлы — по схеме Романова", "points" to "точка = экспертиза с содержанием", "stage_output_dataset" to "исходные данные для следующей стадии")),
        KindSpec("document_template", "шаблон документа", Layer.L0, null, null, listOf("code", "title", "sections", "nature"), listOf("code", "title", "sections", "nature"), listOf(), mapOf("nature" to listOf("narrative", "registry_view", "mixed")), listOf(), mapOf("code" to "Код", "title" to "Заголовок", "sections" to "Разделы", "nature" to "Род"), emptyMap(), mapOf("sections" to "ожидания полноты по MCR/SRR/SDR/PDR", "nature" to "документ-представление = разделы из запросов")),
        KindSpec("pbs_template", "каркас PBS", Layer.L0, null, null, listOf("nodes"), listOf("nodes"), listOf(), mapOf("nodes.kind" to listOf("system", "segment", "element", "subsystem", "assembly", "unit")), listOf(), mapOf("nodes" to "Узлы"), emptyMap(), emptyMap()),
        KindSpec("interface_template", "типовые стыки", Layer.L0, null, null, listOf("interfaces"), listOf("interfaces"), listOf(), mapOf("interfaces.type" to listOf("RF", "power", "data", "thermal", "mech", "env", "hmi", "org")), listOf(), mapOf("interfaces" to "Стыки"), emptyMap(), emptyMap()),
        KindSpec("architecture_template", "шаблон Arcadia", Layer.L0, null, null, listOf("actors", "capabilities", "functions", "exchanges", "chains"), listOf("actors", "capabilities", "activities", "functions", "exchanges", "chains", "logical_components"), listOf(), mapOf("functions.layer" to listOf("SA", "LA")), listOf(), mapOf("actors" to "Акторы", "capabilities" to "Способности", "activities" to "Мероприятия", "functions" to "Функции", "exchanges" to "Обмены", "chains" to "Цепочки", "logical_components" to "Логические компоненты"), emptyMap(), emptyMap()),
        KindSpec("wbs_template", "типовой WBS", Layer.L0, null, null, listOf("packages"), listOf("packages"), listOf(), emptyMap(), listOf(), mapOf("packages" to "Пакеты"), emptyMap(), emptyMap()),
        KindSpec("model_template", "набор моделей системы", Layer.L0, null, null, listOf("models"), listOf("models"), listOf(), mapOf("models.tool_status" to listOf("calc", "proxy", "build")), listOf(), mapOf("models" to "Модели"), emptyMap(), emptyMap()),
        KindSpec("typical_requirement", "типовое требование (библиотека)", Layer.L0, null, null, listOf("code", "title", "ears_pattern", "statement_template", "category", "verification", "applicability", "version"), listOf("code", "title", "ears_pattern", "statement_template", "category", "measure", "verification", "acceptance_criteria", "applicability", "normative_basis", "version"), listOf(), mapOf("ears_pattern" to listOf("ubiquitous", "event", "state", "unwanted", "optional"), "category" to listOf("functional", "performance", "interface", "operational", "constraint", "safety", "environment")), listOf("measure"), mapOf("code" to "Код", "title" to "Заголовок", "ears_pattern" to "Шаблон EARS", "statement_template" to "Шаблон формулировки", "category" to "Категория", "measure" to "Показатель", "verification" to "Верификация", "acceptance_criteria" to "Критерий приёмки", "applicability" to "Применимость", "normative_basis" to "Нормативное основание", "version" to "Версия"), emptyMap(), mapOf("statement_template" to "с плейсхолдерами {носитель}, {значение}", "version" to "новая редакция подсвечивает экземпляры")),
        KindSpec("questionnaire", "анкета (шаблон запроса данных)", Layer.L0, null, null, listOf("code", "target_kind", "fields"), listOf("code", "target_kind", "fields", "kind_presets"), listOf(), mapOf("target_kind" to listOf("component", "interface"), "fields.paths" to listOf("manual", "shelf", "datasheet]["), "kind_presets" to listOf("platform", "payload", "terminal", "station", "software")), listOf(), mapOf("code" to "Код", "target_kind" to "Вид цели", "fields" to "Поля", "kind_presets" to "Предустановки вида"), emptyMap(), mapOf("kind_presets" to "анкета «бортовое ПО»: cpu_load_avg/peak %, ram МБ, rom МБ, cycle_ms, modes, criticality, rtos, language, kloc, autonomy_days")),
        KindSpec("package_kind", "вид пакета службы", Layer.L0, null, null, listOf("code", "schema", "rules", "sources", "accepted_classes", "version"), listOf("code", "schema", "rules", "sources", "accepted_classes", "version"), listOf(), mapOf("sources" to listOf("intent", "library", "materials", "accepted", "constraints][")), listOf(), mapOf("code" to "Код", "schema" to "Схема", "rules" to "Правила", "sources" to "Источники", "accepted_classes" to "Принятые классы", "version" to "Версия"), emptyMap(), emptyMap()),
        KindSpec("site_catalog", "каталог площадок", Layer.L0, null, null, listOf("sites"), listOf("sites"), listOf(), mapOf("sites.type" to listOf("gcs", "gateway")), listOf(), mapOf("sites" to "Площадки"), emptyMap(), emptyMap()),
        KindSpec("project", "проект", Layer.L1, "1", "active|cancelled", listOf("name", "mission_class", "manager", "phase_current", "group", "example", "standard", "phase_template"), listOf("name", "mission_class", "manager", "phase_current", "group", "example", "knowledge_v2", "standard", "phase_template"), listOf(), mapOf("group" to listOf("work", "example"), "standard" to listOf("NASA-7120")), listOf(), mapOf("name" to "Наименование", "mission_class" to "Класс миссии", "manager" to "Руководитель", "phase_current" to "Текущая фаза", "group" to "Группа", "example" to "Пример", "knowledge_v2" to "Знания v2", "standard" to "Стандарт", "phase_template" to "Шаблон фазы"), emptyMap(), mapOf("name" to "правится в паспорте проекта (карточка), не только при создании", "mission_class" to "правится в паспорте проекта (карточка), не только при создании", "manager" to "правится в паспорте проекта (карточка), не только при создании", "knowledge_v2" to "поле знаний v2 — синтез, сверка, ранг доверия; на прежних проектах выключено, новым ставится умолчанием стенда (ORBITA_KNOWLEDGE_V2_DEFAULT)", "standard" to "имена в интерфейсе; кросс-термины — словарь", "phase_template" to "шаблон текущей фазы; меняется решением точки вместе с phase_current")),
        KindSpec("phase", "фаза проекта", Layer.L1, "1 / KDP", "current|passed|returned", listOf("project", "template", "case_instance_id", "points", "opened_by"), listOf("project", "template", "case_instance_id", "points", "opened_by"), listOf(), emptyMap(), listOf(), mapOf("project" to "Проект", "template" to "Шаблон", "case_instance_id" to "Экземпляр дела", "points" to "Точки", "opened_by" to "Открыл"), emptyMap(), mapOf("case_instance_id" to "Flowable")),
        KindSpec("scene", "сцена", Layer.L1, "по шаблону", "вычисляется: locked|available|active|done", listOf("phase", "template_key"), listOf("phase", "template_key", "responsible", "plan", "output_refs", "node"), listOf(), emptyMap(), listOf(), mapOf("phase" to "Фаза", "template_key" to "Ключ шаблона", "responsible" to "Ответственный", "plan" to "План", "output_refs" to "Выходы", "node" to "Узел"), emptyMap(), mapOf("output_refs" to "заполняется каналами", "node" to "для сцен instantiate_per segment|element")),
        KindSpec("step", "шаг сцены", Layer.L1, "по шаблону", "вычисляется: done по условию", listOf("scene", "key"), listOf("scene", "key", "responsible", "plan"), listOf(), emptyMap(), listOf(), mapOf("scene" to "Сцена", "key" to "Ключ", "responsible" to "Ответственный", "plan" to "План"), emptyMap(), emptyMap()),
        KindSpec("gate", "точка / ворота", Layer.L1, "1", "planned|passed|returned", listOf("phase", "key", "title", "planned_date", "criteria", "kind"), listOf("phase", "key", "title", "planned_date", "criteria", "decision", "kind", "aliases", "expertise", "expertise_answers"), listOf(), mapOf("kind" to listOf("phase", "technology"), "expertise.control_items.maturity" to listOf("С", "Р", "F", "U", "Σ", "Δ", "x", "°"), "expertise_answers.answer" to listOf("yes", "no")), listOf(), mapOf("phase" to "Фаза", "key" to "Ключ", "title" to "Заголовок", "planned_date" to "Плановая дата", "criteria" to "Критерии", "decision" to "Решение", "kind" to "Вид", "aliases" to "Псевдонимы", "expertise" to "Экспертиза", "expertise_answers" to "Ответы экспертизы"), emptyMap(), mapOf("kind" to "веха технологии «TRL n достигнут»", "expertise" to "из ПОЛКА-ПРОЦЕССЫ-РОМАНОВ.expertises_full; коды зрелости — легенда владельца", "expertise_answers" to "ответы чек-листа экспертизы, включая «да»: кто и когда; «нет» рождает замечание")),
        KindSpec("criterion", "критерий ворот", Layer.L1, "по шаблону", "вычисляется: satisfied+reason", listOf("gate", "check", "source_scene", "blocking"), listOf("gate", "check", "source_scene", "blocking"), listOf(), emptyMap(), listOf(), mapOf("gate" to "Точка", "check" to "Проверка", "source_scene" to "Сцена-источник", "blocking" to "Блокирующий"), emptyMap(), mapOf("check" to "id проверки из каталога готовности")),
        KindSpec("decision", "решение точки", Layer.L1, "16, 18, A12", null, listOf("gate", "by", "at", "outcome"), listOf("gate", "by", "at", "outcome", "conditions"), listOf(), mapOf("outcome" to listOf("approve", "return", "terminate", "defer")), listOf(), mapOf("gate" to "Точка", "by" to "Кто", "at" to "Когда", "outcome" to "Исход", "conditions" to "Условия"), emptyMap(), mapOf("by" to "DA")),
        KindSpec("finding", "замечание RFA/RID", Layer.L1, "15–17, A12", "open|closed", listOf("gate", "text", "returns_to_scene", "author"), listOf("gate", "text", "returns_to_scene", "author", "assignee", "due_point"), listOf(), emptyMap(), listOf(), mapOf("gate" to "Точка", "text" to "Текст", "returns_to_scene" to "Возврат в сцену", "author" to "Автор", "assignee" to "Исполнитель", "due_point" to "Срок-точка"), emptyMap(), emptyMap()),
        KindSpec("assignment", "задание", Layer.L1, "любая", "вычисляется: open|done (гаснет закрытием цели)", listOf("target", "assignee", "due_point", "assigned_by"), listOf("target", "assignee", "due_point", "assigned_by"), listOf(), mapOf("target.kind" to listOf("gap", "step")), listOf(), mapOf("target" to "Цель (объект)", "assignee" to "Исполнитель", "due_point" to "Срок-точка", "assigned_by" to "Поручил"), emptyMap(), emptyMap()),
        KindSpec("plan", "план дат", Layer.L1, "1, A1", null, listOf("phase", "gate_dates", "set_by"), listOf("phase", "gate_dates", "scene_windows", "set_by"), listOf(), emptyMap(), listOf(), mapOf("phase" to "Фаза", "gate_dates" to "Даты точек", "scene_windows" to "Окна сцен", "set_by" to "Установил"), emptyMap(), mapOf("scene_windows" to "ответственный сцены — в окне плана; пока не назначен — умолчание из ролей проекта (РП / ведущий СИ) по роли сцены в шаблоне")),
        KindSpec("account", "учётка", Layer.L1, null, "active|disabled", listOf("login", "name", "roles"), listOf("login", "name", "roles", "email"), listOf(), emptyMap(), listOf(), mapOf("login" to "Логин", "name" to "Наименование", "roles" to "Роли", "email" to "Почта"), emptyMap(), emptyMap()),
        KindSpec("history", "запись истории", Layer.L1, "всегда", null, listOf("object_ref", "version", "valid_from", "recorded_at", "actor", "action"), listOf("object_ref", "version", "valid_from", "valid_to", "recorded_at", "actor", "action", "basis"), listOf(), mapOf("action" to listOf("create", "update", "cancel", "baseline", "fix")), listOf(), mapOf("object_ref" to "Объект", "version" to "Версия", "valid_from" to "Действует с", "valid_to" to "Действует до", "recorded_at" to "Записано", "actor" to "Актор", "action" to "Действие", "basis" to "Основание"), emptyMap(), mapOf("basis" to "обязателен для правок Approved/Baseline")),
        KindSpec("intent", "замысел", Layer.L2, "2", "draft|accepted", listOf("for_whom", "what", "where", "horizon", "accepted_by", "accepted_at"), listOf("for_whom", "what", "where", "horizon", "anchors", "accepted_by", "accepted_at"), listOf(), emptyMap(), listOf(), mapOf("for_whom" to "Для кого", "what" to "Что делает", "where" to "Где", "horizon" to "Горизонт", "anchors" to "Якоря", "accepted_by" to "Принял", "accepted_at" to "Принято когда"), emptyMap(), emptyMap()),
        KindSpec("material", "входной документ (материал)", Layer.L2, "2", null, listOf("authority", "title", "file", "origin", "doc_version", "doc_date", "classification", "language", "role"), listOf("authority", "type", "title", "file", "origin", "doc_version", "doc_date", "valid_until", "classification", "source_marks", "language", "canon", "map", "harvest", "supersedes", "in_prompt_blocks", "role", "summary", "contribution", "parse_run", "accept_mode", "usefulness", "profile"), listOf(), mapOf("authority" to listOf("mandatory", "expert", "reference", "doubtful"), "type" to listOf("mission_memo", "tor", "directive", "normative", "datasheet", "quote", "external_icd", "external_model", "analysis", "heritage", "regulatory_decision", "reference"), "classification" to listOf("open", "dsp", "commercial", "state_secret"), "language" to listOf("ru", "en"), "role" to listOf("charter", "tor", "regulatory", "context", "supplier", "heritage"), "accept_mode" to listOf("whole", "sections", "selective", "context_only", "rejected")), listOf(), mapOf("authority" to "Ранг доверия", "type" to "Тип", "title" to "Заголовок", "file" to "Файл", "origin" to "Происхождение", "doc_version" to "Версия документа", "doc_date" to "Дата документа", "valid_until" to "Срок действия", "classification" to "Гриф", "source_marks" to "Метки источников", "language" to "Язык", "canon" to "Канон", "map" to "Карта", "harvest" to "Урожай", "supersedes" to "Заменяет", "in_prompt_blocks" to "Блоки в промпт", "role" to "Роль", "summary" to "Резюме", "contribution" to "Вклад", "parse_run" to "Прогон разбора", "accept_mode" to "Режим приёма", "usefulness" to "Полезность", "profile" to "Профиль"), emptyMap(), mapOf("authority" to "ранг доверия источника — обязательный · экспертный · справочный · сомнительный; наследуется фактами; в противоречии подсказывает, решает человек", "type" to "режим разбора (tor · datasheet · normative) выводится заданием и профилем, НЕ поле ввода; доверие — в authority", "file" to "оригинал неизменяем", "origin" to "кто выпустил", "doc_version" to "версия самого документа", "valid_until" to "НПА, КП, решения", "classification" to "state_secret — только карточка-ссылка", "source_marks" to "метки [И]/[В]/[П] в тексте", "canon" to "Д1; нет для гостайны/бинарных", "harvest" to "Д2 по типу: full|registry|parametric|structural|none", "supersedes" to "предыдущая версия входного", "in_prompt_blocks" to "умолчание по типу", "role" to "что документу позволено порождать; charter в проекте один", "summary" to "3–5 строк, порождается при разборе: о чём, что полезного, чего нет", "usefulness" to "вклад + оценка человека", "profile" to "доли по блокам — постановка · параметры · нормы · оценки (Д2а); ставит разбор, не инженер; режим атомизации выбирается по профилю блока")),
        KindSpec("proposal", "предложение службы / пакета", Layer.L2, "любая", "pending|closed", listOf("package_kind", "source", "items", "verdict", "decision"), listOf("package_kind", "source", "items", "fingerprint", "verdict", "decision", "target", "diff_field"), listOf(), mapOf("items.source_mark" to listOf("И", "В", "П"), "items.decision" to listOf("pending", "accepted", "rejected", "rework"), "verdict" to listOf("new", "augment", "contradict", "confirm"), "decision" to listOf("pending", "accepted", "rejected", "deferred")), listOf(), mapOf("package_kind" to "Вид пакета", "source" to "Источник", "items" to "Элементы", "fingerprint" to "Отпечаток", "verdict" to "Вердикт", "decision" to "Решение", "target" to "Цель (объект)", "diff_field" to "Поле различия"), emptyMap(), mapOf("verdict" to "вердикт сверки о кандидате", "decision" to "решение человека", "target" to "принятое, о котором вердикт")),
        KindSpec("stakeholder", "стейкхолдер / актор", Layer.L2, "3", null, listOf("name", "role", "interest"), listOf("name", "role", "interest", "scale", "establishes", "influence", "power", "attitude", "liaison", "normatives"), listOf(), mapOf("role" to listOf("customer", "regulator", "operator", "consumer", "supplier", "partner", "established"), "influence" to listOf("decides", "influences", "informed"), "attitude" to listOf("supports", "neutral", "resists")), listOf("scale"), mapOf("name" to "Наименование", "role" to "Роль", "interest" to "Интерес", "scale" to "Масштаб", "establishes" to "Учреждается", "influence" to "Влияние", "power" to "Сила", "attitude" to "Отношение", "liaison" to "Ответственный за взаимодействие", "normatives" to "Нормативы"), emptyMap(), mapOf("influence" to "карта ОНТОЛОГИЯ-ФОРМИРОВАНИЯ.influence_map; значение модели снимается; инженер правит на месте", "power" to "оценка человека 1–5; пусто до сцены 3", "attitude" to "поддерживает · нейтрален · сопротивляется", "liaison" to "ответственный за взаимодействие (учётка)", "normatives" to "для регуляторов — какие акты несёт")),
        KindSpec("need", "нужда", Layer.L2, "3", null, listOf("statement", "stakeholder", "qos_class", "coverage_expected"), listOf("statement", "stakeholder", "qos_class", "anchors", "coverage_expected"), listOf(), mapOf("coverage_expected" to listOf("service", "constraint", "programme", "requirement")), listOf(), mapOf("statement" to "Формулировка", "stakeholder" to "Сторона", "qos_class" to "Класс обслуживания", "anchors" to "Якоря", "coverage_expected" to "Чем закрывается"), emptyMap(), mapOf("stakeholder" to "owns", "qos_class" to "один или несколько классов из текста; сервис уточняет один; TBR допустим до сцены 6", "coverage_expected" to "чем закрывается нужда; умолчание из роли носителя (заказчик/оператор/потребитель/учреждаемый → service; регулятор → constraint; поставщик/партнёр → programme); правит инженер")),
        KindSpec("goal", "цель", Layer.L2, "4", null, listOf("statement", "measure", "year", "needs"), listOf("statement", "measure", "year", "needs"), listOf(), emptyMap(), listOf("measure"), mapOf("statement" to "Формулировка", "measure" to "Показатель", "year" to "Год", "needs" to "Нужды"), emptyMap(), mapOf("needs" to "covers")),
        KindSpec("constraint", "ограничение Р", Layer.L2, "5", null, listOf("code", "type", "statement"), listOf("code", "type", "statement", "cancelled", "bound"), listOf(), mapOf("type" to listOf("technical", "programmatic", "launch", "regulatory", "financial")), listOf(), mapOf("code" to "Код", "type" to "Тип", "statement" to "Формулировка", "cancelled" to "Отменено", "bound" to "Граница"), emptyMap(), mapOf("bound" to "Числовая граница рамки, если ограничение её задаёт: `key` — что меряем (mass, power, data), `op` — оператор (le, ge, lt, gt), `value` и `unit` — сама граница. Без этого поля ограничение остаётся текстом и НИЧЕГО не сторожит: свёртка не может сказать «106 кг > Р2», потому что не знает, что Р2 — про массу и про 100.")),
        KindSpec("service", "сервис", Layer.L2, "6", null, listOf("name", "needs", "qos_class", "target_measure"), listOf("name", "needs", "qos_class", "target_measure"), listOf(), emptyMap(), listOf("target_measure"), mapOf("name" to "Наименование", "needs" to "Нужды", "qos_class" to "Класс обслуживания", "target_measure" to "Целевой показатель"), emptyMap(), mapOf("needs" to "covers")),
        KindSpec("capability", "способность (OC)", Layer.L2, "6 / A", null, listOf("code", "name", "traced_to"), listOf("code", "name", "traced_to"), listOf(), emptyMap(), listOf(), mapOf("code" to "Код", "name" to "Наименование", "traced_to" to "Трассируется к"), emptyMap(), emptyMap()),
        KindSpec("operational_activity", "операционная активность", Layer.L2, "9", null, listOf("name", "actor"), listOf("name", "actor", "description"), listOf(), emptyMap(), listOf(), mapOf("name" to "Наименование", "actor" to "Актор", "description" to "Описание"), emptyMap(), emptyMap()),
        KindSpec("scenario", "сценарий операций = цепочка", Layer.L2, "9, A3", null, listOf("name", "layer", "steps"), listOf("name", "layer", "steps", "mode", "capability"), listOf(), mapOf("layer" to listOf("OA", "SA")), listOf(), mapOf("name" to "Наименование", "layer" to "Слой", "steps" to "Шаги", "mode" to "Режим", "capability" to "Способность"), emptyMap(), mapOf("steps" to "участник шага — узел состава, сторона (актор) или внешняя система")),
        KindSpec("requirement", "требование", Layer.L3, "8, 9, A4, A5", "Draft|Baseline", listOf("level", "code", "title", "statement", "category", "priority", "carrier", "verification_method", "source", "ears_pattern"), listOf("level", "code", "title", "statement", "category", "priority", "measure", "carrier", "verification_method", "source", "acceptance_criteria", "normative_basis", "ears_pattern", "template_ref", "applicability", "deviation_rationale", "after_baseline_changed", "lint_acknowledged"), listOf(), mapOf("level" to listOf("project", "scenario", "system", "subsystem", "interface"), "category" to listOf("functional", "performance", "interface", "operational", "constraint", "safety", "environment", "regulatory", "security", "data"), "source.kind" to listOf("goal", "need", "constraint", "requirement", "material"), "ears_pattern" to listOf("ubiquitous", "event", "state", "unwanted", "optional"), "applicability" to listOf("applied", "applied_with_deviation", "not_applicable")), listOf("measure"), mapOf("level" to "Уровень", "code" to "Код", "title" to "Заголовок", "statement" to "Формулировка", "category" to "Категория", "priority" to "Приоритет", "measure" to "Показатель", "carrier" to "Носитель", "verification_method" to "Метод верификации", "source" to "Источник", "acceptance_criteria" to "Критерий приёмки", "normative_basis" to "Нормативное основание", "ears_pattern" to "Шаблон EARS", "template_ref" to "Типовое требование", "applicability" to "Применимость", "deviation_rationale" to "Обоснование отклонения", "after_baseline_changed" to "Изменено после базирования", "lint_acknowledged" to "Пометы линта приняты"), mapOf("level" to "accept:default(project на сцене 8)", "code" to "accept:system", "title" to "accept", "statement" to "accept", "category" to "baseline:proposed", "priority" to "baseline:default(medium)", "measure" to "baseline|tbr", "carrier" to "baseline", "verification_method" to "SRR:tbd_allowed", "source" to "accept:from_basis", "acceptance_criteria" to "baseline", "normative_basis" to "if_regulatory", "ears_pattern" to "accept:auto"), mapOf("measure" to "обязателен для performance", "carrier" to "тип по уровню; обязателен к базированию", "verification_method" to "TBD допустим до SRR", "acceptance_criteria" to "обязателен к базированию", "ears_pattern" to "шаблон формулировки EARS", "template_ref" to "экземпляр типового", "applicability" to "обязательна при template_ref", "deviation_rationale" to "обязательна при deviation/not_applicable", "after_baseline_changed" to "версия > версии в последнем baseline", "lint_acknowledged" to "«принять как есть»: помета линта осознанно оставлена")),
        KindSpec("link", "связь (объект)", Layer.L3, "любая", null, listOf("type", "from", "to", "rationale", "created_by"), listOf("type", "subtype", "from", "to", "rationale", "created_by", "suspect", "confirmed_by", "confirmed_at", "revision_expected", "sensitivity"), listOf(), mapOf("type" to listOf("owns", "covers", "derives_from", "allocated_to", "satisfied_by", "realized_by", "allocation", "flows_over", "illustrated_by", "traced_to", "verifies", "conflicts_with", "snapshot_of", "input_of", "output_of", "pairs_with", "external_identity", "deployed_on", "uses_item", "depends_on_technology", "derived_from_fact", "about", "supports", "contradicts", "supersedes", "confirms", "same_as", "refines"), "subtype" to listOf("decomposition", "derivation", "refinement")), listOf(), mapOf("type" to "Тип", "subtype" to "Подтип", "from" to "Откуда", "to" to "Куда", "rationale" to "Обоснование", "created_by" to "Создал", "suspect" to "Под вопросом", "confirmed_by" to "Подтвердил", "confirmed_at" to "Подтверждено когда", "revision_expected" to "Ожидается редакция", "sensitivity" to "Чувствительность"), emptyMap(), mapOf("subtype" to "для derives_from", "rationale" to "обязателен для derives_from,satisfied_by,realized_by,conflicts_with,external_identity", "suspect" to "конец изменился после baseline", "revision_expected" to "для depends_on_technology", "sensitivity" to "что пересматривается после созревания")),
        KindSpec("function", "функция", Layer.L3, "7, A5", null, listOf("code", "name", "layer", "allocated_to"), listOf("code", "name", "layer", "allocated_to"), listOf(), mapOf("layer" to listOf("SA", "LA")), listOf(), mapOf("code" to "Код", "name" to "Наименование", "layer" to "Слой", "allocated_to" to "Распределено на"), emptyMap(), mapOf("allocated_to" to "≥1 к SDR")),
        KindSpec("exchange", "обмен", Layer.L3, "A5", null, listOf("code", "name", "source_function", "target", "interface"), listOf("code", "name", "source_function", "target", "interface", "payload"), listOf(), emptyMap(), listOf(), mapOf("code" to "Код", "name" to "Наименование", "source_function" to "Исходная функция", "target" to "Цель (объект)", "interface" to "Стык", "payload" to "Содержимое"), emptyMap(), mapOf("interface" to "flows_over")),
        KindSpec("functional_chain", "функциональная цепочка", Layer.L3, "9, A3", null, listOf("code", "name", "steps"), listOf("code", "name", "steps", "ack_steps", "capability"), listOf(), emptyMap(), listOf(), mapOf("code" to "Код", "name" to "Наименование", "steps" to "Шаги", "ack_steps" to "Подтверждённые шаги", "capability" to "Способность"), emptyMap(), emptyMap()),
        KindSpec("logical_component", "логический компонент", Layer.L3, "A5", null, listOf("code", "name", "functions", "deployed_to"), listOf("code", "name", "functions", "deployed_to"), listOf(), emptyMap(), listOf(), mapOf("code" to "Код", "name" to "Наименование", "functions" to "Функции", "deployed_to" to "Развёрнуто на"), emptyMap(), emptyMap()),
        KindSpec("component", "узел состава (определение)", Layer.L3, "7, A5", null, listOf("code", "name", "level", "nature", "kind"), listOf("code", "name", "parent", "level", "nature", "kind", "external", "external_identity", "wbs_pair", "template_ref", "applicability", "deviation_rationale", "structure_readonly", "standards", "maturity_tailoring"), listOf(), mapOf("nature" to listOf("node", "behaviour"), "kind" to listOf("system", "segment", "element", "subsystem", "assembly", "unit"), "applicability" to listOf("applied", "applied_with_deviation", "not_applicable"), "maturity_tailoring.action" to listOf("add", "remove", "shift")), listOf(), mapOf("code" to "Код", "name" to "Наименование", "parent" to "Родитель", "level" to "Уровень", "nature" to "Род", "kind" to "Вид", "external" to "Внешний", "external_identity" to "Внешняя идентичность", "wbs_pair" to "Пара WBS", "template_ref" to "Ссылка на шаблон", "applicability" to "Применимость", "deviation_rationale" to "Обоснование отклонения", "structure_readonly" to "Структура только чтение", "standards" to "Стандарты", "maturity_tailoring" to "Адаптация лестницы"), emptyMap(), mapOf("parent" to "корень — без", "nature" to "behaviour обязан быть развёрнут на node", "structure_readonly" to "true, если external_identity задан и модель есть", "maturity_tailoring" to "отклонение от лестницы шаблона; hard-грани не снимаются")),
        KindSpec("component_usage", "вхождение ×N", Layer.L3, "7", null, listOf("definition", "quantity"), listOf("definition", "parent_usage", "quantity", "role", "orbit"), listOf(), emptyMap(), listOf(), mapOf("definition" to "Определение", "parent_usage" to "Родительское вхождение", "quantity" to "Количество", "role" to "Роль", "orbit" to "Орбита"), emptyMap(), mapOf("orbit" to "для КА в подгруппе · наклонение для Walker, ЛВУ для ССО — одно из двух")),
        KindSpec("interface", "стык", Layer.L3, "7, A5", null, listOf("code", "name", "type", "a", "b", "direction", "requirement_classes"), listOf("code", "name", "type", "a", "b", "direction", "standard", "params", "icd_sections", "requirement_classes"), listOf(), mapOf("type" to listOf("RF", "power", "data", "thermal", "mech", "env", "hmi", "org"), "direction" to listOf("uni", "bi", "static", "org")), listOf(), mapOf("code" to "Код", "name" to "Наименование", "type" to "Тип", "a" to "Сторона A", "b" to "Сторона B", "direction" to "Направление", "standard" to "Стандарт", "params" to "Параметры", "icd_sections" to "Разделы ICD", "requirement_classes" to "Классы требований"), emptyMap(), emptyMap()),
        KindSpec("model_element", "внешний элемент модели", Layer.L3, "A5", null, listOf("tool", "model_id", "uuid", "type", "layer", "name_snapshot", "refreshed_at", "fixture"), listOf("tool", "model_id", "uuid", "type", "layer", "name_snapshot", "refreshed_at", "fixture"), listOf(), mapOf("tool" to listOf("capella"), "type" to listOf("OperationalCapability", "SystemFunction", "LogicalFunction", "LogicalComponent", "PhysicalComponent", "FunctionalExchange", "FunctionalChain", "Diagram"), "layer" to listOf("OA", "SA", "LA", "PA")), listOf(), mapOf("tool" to "Инструмент", "model_id" to "Идентификатор модели", "uuid" to "UUID", "type" to "Тип", "layer" to "Слой", "name_snapshot" to "Имя (снимок)", "refreshed_at" to "Обновлено", "fixture" to "Фикстура"), emptyMap(), mapOf("uuid" to "истина идентичности")),
        KindSpec("constellation_variant", "вариант построения", Layer.L3, "7, A6", null, listOf("name", "subgroups", "working"), listOf("name", "subgroups", "working"), listOf(), mapOf("subgroups.pattern" to listOf("walker_delta", "walker_star", "sso")), listOf(), mapOf("name" to "Наименование", "subgroups" to "Подгруппы", "working" to "В работе"), emptyMap(), mapOf("subgroups" to "наклонение для Walker, ЛВУ для ССО — одно из двух")),
        KindSpec("baseline_concept", "базовая концепция", Layer.L3, "7", null, listOf("variant", "rationale", "rejected", "descopes", "decided_by", "at"), listOf("variant", "rationale", "rejected", "descopes", "decided_by", "at"), listOf(), emptyMap(), listOf(), mapOf("variant" to "Вариант", "rationale" to "Обоснование", "rejected" to "Отклонено", "descopes" to "Отсечения объёма", "decided_by" to "Решил", "at" to "Когда"), emptyMap(), emptyMap()),
        KindSpec("technology", "технология / TRL", Layer.L3, "10, A7", null, listOf("name", "component", "trl_current", "trl_required", "required_by"), listOf("name", "component", "trl_current", "trl_required", "required_by", "gap_plan", "fallback", "maturation_package", "milestone", "fallback_component", "decision_criteria"), listOf(), emptyMap(), listOf(), mapOf("name" to "Наименование", "component" to "Узел", "trl_current" to "TRL текущий", "trl_required" to "TRL требуемый", "required_by" to "Требуется к", "gap_plan" to "План закрытия разрыва", "fallback" to "Резерв", "maturation_package" to "Пакет созревания", "milestone" to "Веха", "fallback_component" to "Резервный узел", "decision_criteria" to "Критерии решения"), emptyMap(), mapOf("maturation_package" to "обязателен при trl_current<trl_required к SDR", "fallback_component" to "узел-резерв", "decision_criteria" to "критерии перехода на резерв (Прил. 5)")),
        KindSpec("risk", "риск", Layer.L3, "11, A8", "open|closed", listOf("statement", "cec", "category", "probability", "impact", "strategy", "measures", "owner", "due_point"), listOf("statement", "cec", "category", "probability", "impact", "strategy", "measures", "owner", "due_point", "refs"), listOf(), mapOf("category" to listOf("technical", "cost", "schedule", "safety", "regulatory", "security", "programmatic"), "strategy" to listOf("mitigate", "accept", "transfer", "avoid")), listOf(), mapOf("statement" to "Формулировка", "cec" to "Условие · событие · последствие", "category" to "Категория", "probability" to "Вероятность", "impact" to "Последствия", "strategy" to "Стратегия", "measures" to "Меры", "owner" to "Владелец", "due_point" to "Срок-точка", "refs" to "Ссылки"), emptyMap(), mapOf("due_point" to "срок — любая веха (gate.kind phase|technology); точка фазы считает сроки по дате ≤ своей")),
        KindSpec("debris_assessment", "оценка засорения (ODA): активный увод и пассивный сход", Layer.L3, "11, A9", null, listOf("variant", "active_lifetime_years", "deorbit_dv", "passive_lifetime_years", "normative_active", "normative_passive", "compliant_active", "compliant_passive", "atmosphere_model", "ballistic_coefficient", "model_run"), listOf("variant", "active_lifetime_years", "deorbit_dv", "passive_lifetime_years", "normative_active", "normative_passive", "compliant_active", "compliant_passive", "atmosphere_model", "ballistic_coefficient", "model_run"), listOf(), emptyMap(), listOf("deorbit_dv", "ballistic_coefficient"), mapOf("variant" to "Вариант", "active_lifetime_years" to "Время существования после увода, лет", "deorbit_dv" to "Δv увода", "passive_lifetime_years" to "Пассивный сход, лет", "normative_active" to "Норма активного увода", "normative_passive" to "Норма пассивного схода", "compliant_active" to "Соответствие: активный увод", "compliant_passive" to "Соответствие: пассивный сход", "atmosphere_model" to "Модель атмосферы", "ballistic_coefficient" to "Баллистический коэффициент", "model_run" to "Прогон модели"), emptyMap(), mapOf("active_lifetime_years" to "время существования после увода ДУ", "passive_lifetime_years" to "пассивный сход при отказе ДУ", "normative_active" to "норма активного увода (Б1: ≤ 5 лет)", "normative_passive" to "норма пассивного схода (≤ 25 лет)", "atmosphere_model" to "прокси/модель — подписан", "ballistic_coefficient" to "m/(Cd·A)")),
        KindSpec("system_model", "запись модели", Layer.L4, "7, A6", "not_built|proxy|calc", listOf("template_code", "inputs", "verification_status"), listOf("template_code", "inputs", "interface_ref", "last_run", "verification_status", "evaluation_criteria"), listOf(), mapOf("verification_status" to listOf("unverified", "verified", "validated")), listOf(), mapOf("template_code" to "Код шаблона", "inputs" to "Входы", "interface_ref" to "Ссылка на стык", "last_run" to "Последний прогон", "verification_status" to "Статус верификации", "evaluation_criteria" to "Критерии оценки"), emptyMap(), mapOf("evaluation_criteria" to "критерии оценки модели (мероприятие «критерии оценки моделей»)")),
        KindSpec("model_run", "выход расчёта", Layer.L4, "при расчёте", null, listOf("model", "version", "inputs_snapshot", "outputs", "tool", "proxy", "at", "by"), listOf("model", "version", "inputs_snapshot", "outputs", "tool", "proxy", "at", "by"), listOf(), emptyMap(), listOf(), mapOf("model" to "Модель", "version" to "Версия", "inputs_snapshot" to "Снимок входов", "outputs" to "Выходы", "tool" to "Инструмент", "proxy" to "Прокси", "at" to "Когда", "by" to "Кто"), emptyMap(), emptyMap()),
        KindSpec("metric", "метрика сравнения", Layer.L4, "7", null, listOf("variant", "code", "measure", "group", "direction"), listOf("variant", "code", "measure", "threshold", "group", "proxy", "direction", "model_run"), listOf(), mapOf("group" to listOf("A", "B", "V", "G"), "direction" to listOf("max", "min")), listOf("measure"), mapOf("variant" to "Вариант", "code" to "Код", "measure" to "Показатель", "threshold" to "Порог", "group" to "Группа", "proxy" to "Прокси", "direction" to "Направление", "model_run" to "Прогон модели"), emptyMap(), mapOf("threshold" to "порог отсева: {op,value,unit}; отсеянный вариант называет порог по имени", "group" to "группа сравнения: покрытие · задержка · стоимость · риск (четыре группы AoA)", "direction" to "куда лучше: больше или меньше", "model_run" to "откуда значение; пусто — ручное/прокси с пометой")),
        KindSpec("budget", "бюджет / свёртка", Layer.L4, "7, A5", null, listOf("kind", "root", "reserve_policy"), listOf("kind", "root", "reserve_policy"), listOf(), mapOf("kind" to listOf("mass", "power", "energy", "link", "dv", "data", "compute")), listOf(), mapOf("kind" to "Вид", "root" to "Корень", "reserve_policy" to "Политика резервов"), emptyMap(), emptyMap()),
        KindSpec("verification_event", "событие верификации", Layer.L4, "A4+", null, listOf("requirement", "method", "result", "at", "by"), listOf("requirement", "method", "result", "evidence", "at", "by"), listOf(), mapOf("result" to listOf("pass", "fail", "partial")), listOf(), mapOf("requirement" to "Требование", "method" to "Метод", "result" to "Результат", "evidence" to "Свидетельство", "at" to "Когда", "by" to "Кто"), emptyMap(), emptyMap()),
        KindSpec("wbs_package", "пакет работ", Layer.L4, "7, 12, A10", null, listOf("code", "name", "cross_cutting"), listOf("code", "name", "parent", "cross_cutting", "pbs_refs", "phase_scenes", "estimate"), listOf(), emptyMap(), listOf(), mapOf("code" to "Код", "name" to "Наименование", "parent" to "Родитель", "cross_cutting" to "Сквозной", "pbs_refs" to "Узлы состава", "phase_scenes" to "Сцены фазы", "estimate" to "Оценка"), emptyMap(), emptyMap()),
        KindSpec("cost_estimate", "оценка стоимости / сроков", Layer.L4, "12, A10", null, listOf("scope", "range", "assumptions", "method", "date"), listOf("scope", "range", "assumptions", "method", "date", "cadre", "includes_maturation"), listOf(), mapOf("method" to listOf("rom", "parametric", "bottom_up")), listOf(), mapOf("scope" to "Область", "range" to "Диапазон", "assumptions" to "Допущения", "method" to "Метод", "date" to "Дата", "cadre" to "Состав команды", "includes_maturation" to "Включает созревание"), emptyMap(), mapOf("includes_maturation" to "все технологии с разрывом TRL имеют пакет в оценке")),
        KindSpec("data_request", "запрос данных (экземпляр анкеты)", Layer.L4, "7+", "вычисляется: maturity{required_now,missing}", listOf("questionnaire", "target", "fields"), listOf("questionnaire", "target", "fields"), listOf(), emptyMap(), listOf(), mapOf("questionnaire" to "Анкета", "target" to "Цель (объект)", "fields" to "Поля"), emptyMap(), emptyMap()),
        KindSpec("document", "документ", Layer.L5, "9, 13, 14, A2, A3, A11", "Draft → Preliminary → Approved → Baseline (по baseline документа)", listOf("template", "code", "title", "sections", "owner", "nature"), listOf("template", "code", "title", "sections", "owner", "nature"), listOf(), mapOf("nature" to listOf("narrative", "registry_view", "mixed")), listOf(), mapOf("template" to "Шаблон", "code" to "Код", "title" to "Заголовок", "sections" to "Разделы", "owner" to "Владелец", "nature" to "Род"), emptyMap(), emptyMap()),
        KindSpec("section", "раздел", Layer.L5, "с документом", "вычисляется: completeness{done,total,missing[]} · support_changed{flag,diff[]}", listOf("document", "no", "title", "expects_snapshot"), listOf("document", "no", "title", "elements", "expects_snapshot"), listOf(), emptyMap(), listOf(), mapOf("document" to "Документ", "no" to "Номер", "title" to "Заголовок", "elements" to "Элементы", "expects_snapshot" to "Ожидания (снимок)"), emptyMap(), mapOf("expects_snapshot" to "из шаблона на текущую ступень")),
        KindSpec("release", "выпуск", Layer.L5, "13, A12", null, listOf("document", "rendering", "version", "print_files", "authors", "released_by", "at"), listOf("document", "rendering", "version", "print_files", "authors", "released_by", "at"), listOf(), mapOf("print_files.format" to listOf("docx", "pdf", "html")), listOf(), mapOf("document" to "Документ", "rendering" to "Рендеринг", "version" to "Версия", "print_files" to "Файлы печати", "authors" to "Авторы", "released_by" to "Выпустил", "at" to "Когда"), emptyMap(), mapOf("rendering" to "принятый")),
        KindSpec("result", "результат в библиотеке", Layer.L5, "с выпуском", null, listOf("release", "authors"), listOf("release", "authors", "generalize_to"), listOf(), emptyMap(), listOf(), mapOf("release" to "Выпуск", "authors" to "Авторы", "generalize_to" to "Обобщить в"), emptyMap(), emptyMap()),
        KindSpec("baseline_snapshot", "снимок базирования", Layer.L5, "базирование", null, listOf("project", "sdoc_path", "hash", "by", "at"), listOf("project", "sdoc_path", "hash", "by", "at", "requirements_count", "document", "tag", "commit", "elements"), listOf(), emptyMap(), listOf(), mapOf("project" to "Проект", "sdoc_path" to "Путь .sdoc", "hash" to "Хеш", "by" to "Кто", "at" to "Когда", "requirements_count" to "Число требований", "document" to "Документ", "tag" to "Тег", "commit" to "Коммит", "elements" to "Элементы"), emptyMap(), mapOf("requirements_count" to "Снимок набора требований. У снимка ДОКУМЕНТА этого поля нет: вид один, а базируют им и набор требований, и документ.", "document" to "Снимок документа: код шаблона, чей текст зафиксирован.", "tag" to "Имя аннотированного тега в репозитории базирований. Тег и есть имя базовой линии для человека: «внутренний обзор».", "commit" to "Коммит, на который встал тег: внешняя проверяемая отметка.", "elements" to "Содержание снимка поэлементно. Диф считается ПО MID и по полям: правка одного тезиса обязана давать расхождение в одном узле, а не «документ изменился».")),
        KindSpec("export", "выгрузка", Layer.L5, "по запросу", null, listOf("type", "scope", "fingerprint", "files", "by", "at"), listOf("type", "scope", "fingerprint", "files", "by", "at", "reqif_profile"), listOf(), mapOf("type" to listOf("reqif", "sdoc", "knowledge", "gate_package"), "reqif_profile" to listOf("ORBITA")), listOf(), mapOf("type" to "Тип", "scope" to "Область", "fingerprint" to "Отпечаток", "files" to "Файлы", "by" to "Кто", "at" to "Когда", "reqif_profile" to "Профиль ReqIF"), emptyMap(), mapOf("reqif_profile" to "атрибуты ReqIF.ForeignID/Name/Text/ChapterName + ORBITA.Level/Category/Priority/MOP.*/Verification/Acceptance/Rationale/Source/Status/Version/Baseline/Carrier/Template/Applicability")),
        KindSpec("import_batch", "импорт", Layer.L5, "2, A4", null, listOf("type", "source_file", "proposal", "foreign_attributes_kept"), listOf("type", "source_file", "proposal", "foreign_attributes_kept"), listOf(), mapOf("type" to listOf("reqif", "sdoc", "package")), listOf(), mapOf("type" to "Тип", "source_file" to "Файл источника", "proposal" to "Предложение", "foreign_attributes_kept" to "Чужие атрибуты сохранены"), emptyMap(), emptyMap()),
        KindSpec("ai_call", "вызов службы (журнал)", Layer.L5, "любая", null, listOf("package_kind", "outcome", "at", "by"), listOf("package_kind", "model", "tokens_in", "tokens_out", "outcome", "reason", "fingerprint", "at", "by"), listOf(), mapOf("outcome" to listOf("ok", "error", "aborted")), listOf(), mapOf("package_kind" to "Вид пакета", "model" to "Модель", "tokens_in" to "Токены на входе", "tokens_out" to "Токены на выходе", "outcome" to "Исход", "reason" to "Причина", "fingerprint" to "Отпечаток", "at" to "Когда", "by" to "Кто"), emptyMap(), emptyMap()),
        KindSpec("parameter", "значение параметра узла", Layer.L3, "7, A5+", "вычисляется: filled|missing|tbr", listOf("target", "key", "measure", "origin", "required_to", "maturity_class", "uncertainty"), listOf("target", "key", "measure", "origin", "source", "required_to", "basis", "maturity_class", "uncertainty"), listOf(), mapOf("origin" to listOf("manual", "datasheet", "shelf", "computed", "example"), "maturity_class" to listOf("estimated", "modified", "off_the_shelf", "measured")), listOf("measure"), mapOf("target" to "Цель (объект)", "key" to "Ключ", "measure" to "Показатель", "origin" to "Происхождение", "source" to "Источник", "required_to" to "Обязателен к", "basis" to "Основание", "maturity_class" to "Класс зрелости", "uncertainty" to "Неопределённость"), emptyMap(), mapOf("key" to "ключ анкеты", "measure" to "срок — любая веха (gate.kind phase|technology); точка фазы считает сроки по дате ≤ своей", "source" to "обязателен для datasheet и computed", "basis" to "обязателен при правке после baseline", "maturity_class" to "резерв по классу", "uncertainty" to "по ступени, если не задано")),
        KindSpec("baseline", "именованный снимок набора", Layer.L1, "8, A4, точки", "immutable", listOf("name", "kind", "gate", "items", "sdoc_path", "hash", "by", "at"), listOf("name", "kind", "gate", "items", "sdoc_path", "hash", "by", "at", "diff_from"), listOf(), mapOf("kind" to listOf("functional", "allocated", "product"), "items.firmness" to listOf("firm", "conditional")), listOf(), mapOf("name" to "Наименование", "kind" to "Вид", "gate" to "Точка", "items" to "Элементы", "sdoc_path" to "Путь .sdoc", "hash" to "Хеш", "by" to "Кто", "at" to "Когда", "diff_from" to "Различия от"), emptyMap(), mapOf("name" to "SRR · SDR · KDP-B · …", "kind" to "класс базовой линии CM")),
        KindSpec("typical_component", "типовой компонент (библиотека)", Layer.L0, null, null, listOf("code", "name", "kind", "applicability", "nature", "role", "ladder"), listOf("code", "name", "kind", "applicability", "typical_requirements", "nature", "role", "ladder", "typical_functions", "typical_interfaces", "models", "standards", "verification", "typical_risks", "hard_facets"), listOf(), mapOf("kind" to listOf("system", "segment", "element", "subsystem", "assembly", "unit"), "nature" to listOf("node", "behaviour"), "role" to listOf("node", "behaviour", "facility", "terminal", "external")), listOf(), mapOf("code" to "Код", "name" to "Наименование", "kind" to "Вид", "applicability" to "Применимость", "typical_requirements" to "Типовые требования", "nature" to "Род", "role" to "Роль", "ladder" to "Лестница зрелости", "typical_functions" to "Типовые функции", "typical_interfaces" to "Типовые стыки", "models" to "Модели", "standards" to "Стандарты", "verification" to "Верификация", "typical_risks" to "Типовые риски", "hard_facets" to "Жёсткие грани"), emptyMap(), mapOf("role" to "шаблон рода по умолчанию", "hard_facets" to "грани, обязательные регламентом, не подлежат tailoring")),
        KindSpec("exchange_item", "элемент обмена", Layer.L3, "A5", null, listOf("code", "name", "type", "elements"), listOf("code", "name", "type", "elements", "exchanges"), listOf(), mapOf("type" to listOf("flow", "operation", "event", "shared_data")), listOf(), mapOf("code" to "Код", "name" to "Наименование", "type" to "Тип", "elements" to "Элементы", "exchanges" to "Обмены"), emptyMap(), mapOf("exchanges" to "где используется")),
        KindSpec("data_type", "тип данных", Layer.L0, "A5", null, listOf("code", "name", "base"), listOf("code", "name", "base", "unit", "range", "enum_values", "fields"), listOf(), mapOf("base" to listOf("int", "float", "bool", "enum", "string", "bytes", "struct")), listOf(), mapOf("code" to "Код", "name" to "Наименование", "base" to "База", "unit" to "Единица", "range" to "Диапазон", "enum_values" to "Значения", "fields" to "Поля"), emptyMap(), mapOf("unit" to "обязателен для числовых величин", "fields" to "для struct")),
        KindSpec("state_machine", "режимы и состояния компонента", Layer.L3, "A5", null, listOf("owner", "states", "initial", "transitions"), listOf("owner", "states", "initial", "transitions"), listOf(), mapOf("states.kind" to listOf("mode", "state"), "transitions.trigger" to listOf("exchange", "event", "timer")), listOf(), mapOf("owner" to "Владелец", "states" to "Состояния", "initial" to "Начальное", "transitions" to "Переходы"), emptyMap(), emptyMap()),
        KindSpec("configuration_item", "конфигурационная единица", Layer.L4, "A5", null, listOf("code", "component", "type", "responsible"), listOf("code", "component", "type", "responsible"), listOf(), mapOf("type" to listOf("HW", "SW", "FW", "DOC")), listOf(), mapOf("code" to "Код", "component" to "Узел", "type" to "Тип", "responsible" to "Ответственный"), emptyMap(), emptyMap()),
        KindSpec("product_version", "версия изделия (не записи)", Layer.L4, "A7+", "mockup|flight_test|operations", listOf("ci", "version", "date", "composition"), listOf("ci", "version", "date", "composition", "notes"), listOf(), emptyMap(), listOf(), mapOf("ci" to "Конфигурационная единица", "version" to "Версия", "date" to "Дата", "composition" to "Состав", "notes" to "Заметки"), emptyMap(), mapOf("version" to "семантическая версия изделия", "composition" to "ссылается на baseline записей")),
        KindSpec("intake_task", "задание загрузки", Layer.L2, "любая", "planned|awaiting_accept|executed|rejected", listOf("source", "snapshot", "intent", "intent_kind", "context", "plan", "author"), listOf("source", "snapshot", "intent", "intent_kind", "context", "classification", "plan", "author"), listOf(), mapOf("intent_kind" to listOf("harvest", "shelve_typical", "baseline_candidate", "compare", "update_params", "register_normative", "assess_tor", "context_only", "other")), listOf(), mapOf("source" to "Источник", "snapshot" to "Снимок", "intent" to "Замысел", "intent_kind" to "Вид задания", "context" to "Контекст", "classification" to "Гриф", "plan" to "План", "author" to "Автор"), emptyMap(), mapOf("snapshot" to "URL — рендер headless в PDF+MD", "intent" to "умолчание «разбери по сущностям»", "classification" to "Д2а")),
        KindSpec("fact", "атомарный факт", Layer.L2, "загрузка", "disposition: free|noted|assumed|adopted|rejected|contested|superseded", listOf("kind", "subject", "predicate", "quote", "value", "source", "source_mark", "evidence", "confidence", "as_of", "disposition", "classification", "authority"), listOf("kind", "entity_class", "subject", "predicate", "quote", "value", "source", "source_mark", "source_mark_no", "evidence", "confidence", "as_of", "valid_until", "disposition", "disposition_decision", "assumption", "classification", "authority", "parse_run"), listOf(), mapOf("kind" to listOf("quantity", "capability", "obligation", "framing", "event", "relation", "assessment", "assumption", "external_target", "external_need"), "entity_class" to listOf("requirement", "function", "service", "composition_node", "stakeholder", "constraint", "milestone", "normative_ref"), "source_mark" to listOf("И", "В", "П"), "evidence" to listOf("claimed", "corroborated", "measured", "assumed"), "disposition" to listOf("free", "noted", "assumed", "adopted", "rejected", "contested", "superseded"), "classification" to listOf("open", "dsp", "commercial"), "authority" to listOf("mandatory", "expert", "reference", "doubtful")), listOf("value"), mapOf("kind" to "Вид", "entity_class" to "Класс сущности", "subject" to "Субъект", "predicate" to "Предикат", "quote" to "Цитата", "value" to "Значение", "source" to "Источник", "source_mark" to "Метка источника", "source_mark_no" to "Номер источника", "evidence" to "Свидетельство", "confidence" to "Уверенность", "as_of" to "По состоянию на", "valid_until" to "Срок действия", "disposition" to "Диспозиция", "disposition_decision" to "Решение по диспозиции", "assumption" to "Допущение", "classification" to "Гриф", "authority" to "Ранг доверия", "parse_run" to "Прогон разбора"), emptyMap(), mapOf("entity_class" to "класс сущности ТЗ (правило атомизации ШИП-G-ПРИНЯТ) — сверка разбора с пакетом по классам", "subject" to "ровно одно из двух", "quote" to "дословный фрагмент источника, сверяется с каноном; у ручного факта эксперта — null", "source" to "документ с якорем — или эксперт без якоря (учётка · роль · дата); ровно одно из двух, стережёт Kotlin", "source_mark_no" to "номер источника из списка документа: И1, В10", "disposition_decision" to "обязателен при любой диспозиции кроме free", "assumption" to "обязателен при disposition=assumed; owner и confirm_by спрашивает окно приёма, validation и impact — по желанию", "classification" to "наследуется от источника", "authority" to "наследуется от документа; expert — ручной ввод; ранг подсказывает в противоречии, не выбирает победителя", "parse_run" to "обязателен с шипа 2 (изоляция вклада документа); у фактов, созданных до миграции, — null; обязательность обеспечивают ворота создания, не схема")),
        KindSpec("action", "действие плана загрузки", Layer.L2, "с intake_task", "proposed|accepted|rejected|done", listOf("task", "kind", "target", "preview", "facts", "decision"), listOf("task", "kind", "target", "preview", "facts", "decision"), listOf(), mapOf("kind" to listOf("create_typical", "create_entity", "update_params", "compare", "request_data", "flag_conflict", "create_decision", "create_risk", "attach_context"), "decision" to listOf("pending", "accepted", "rejected")), listOf(), mapOf("task" to "Задача", "kind" to "Вид", "target" to "Цель (объект)", "preview" to "Предпросмотр", "facts" to "Факты", "decision" to "Решение"), emptyMap(), mapOf("preview" to "что создаст/изменит")),
        KindSpec("topic", "тема (предмет фактов до разрешения в сущность)", Layer.L2, "загрузка", "open|resolved", listOf("label"), listOf("label", "resolved_to", "scene", "merged_into"), listOf(), emptyMap(), listOf(), mapOf("label" to "Метка", "resolved_to" to "Разрешена в", "scene" to "Сцена", "merged_into" to "Слито в"), emptyMap(), mapOf("resolved_to" to "обязателен, если есть adopted факты к точке", "merged_into" to "слияние тем по same_as с подтверждением человека; ИИ предлагает, сливает клик")),
        KindSpec("element", "элемент содержания раздела", Layer.L5, "по разделу", "active|removed", listOf("section", "kind", "author", "at", "order"), listOf("section", "kind", "ref", "ref_version", "text", "supports", "query", "author", "at", "order"), listOf(), mapOf("kind" to listOf("fact_ref", "entity_ref", "statement", "query", "figure", "table")), listOf(), mapOf("section" to "Раздел", "kind" to "Вид", "ref" to "Ссылка", "ref_version" to "Версия ссылки", "text" to "Текст", "supports" to "Поддерживает", "query" to "Запрос", "author" to "Автор", "at" to "Когда", "order" to "Порядок"), emptyMap(), mapOf("ref" to "обязателен для fact_ref/entity_ref/figure", "ref_version" to "версия опоры на момент включения", "text" to "только для statement, 1–3 предложения", "supports" to "обязателен для statement с числами", "query" to "для query/table")),
        KindSpec("rendering", "порождённый читаемый текст версии документа", Layer.L5, "базирование/предпросмотр", "draft|reviewed|accepted|superseded", listOf("document", "sections", "prompt_fingerprint", "model"), listOf("document", "baseline", "sections", "prompt_fingerprint", "model", "style_patches", "reviewer", "accepted_at"), listOf(), emptyMap(), listOf(), mapOf("document" to "Документ", "baseline" to "Базовая линия", "sections" to "Разделы", "prompt_fingerprint" to "Отпечаток промпта", "model" to "Модель", "style_patches" to "Правки изложения", "reviewer" to "Рецензент", "accepted_at" to "Принято когда"), emptyMap(), mapOf("baseline" to "null для предпросмотра", "style_patches" to "правки изложения")),
        KindSpec("process_catalog", "каталог процессов СИ (двухстандартный)", Layer.L0, null, null, listOf("code", "name", "group", "orbita_mechanism", "place", "tailoring_allowed"), listOf("code", "name", "npr_7123", "romanov_activity", "iso_15288", "group", "orbita_mechanism", "place", "tailoring_allowed"), listOf(), mapOf("group" to listOf("system_design", "product_realization", "technical_management", "agreement", "organizational", "mbse")), listOf(), mapOf("code" to "Код", "name" to "Наименование", "npr_7123" to "NPR 7123.1", "romanov_activity" to "Мероприятие Романова", "iso_15288" to "ГОСТ ISO 15288", "group" to "Группа", "orbita_mechanism" to "Механизм Орбиты", "place" to "Место", "tailoring_allowed" to "Адаптация допустима"), emptyMap(), mapOf("npr_7123" to "один из 17 процессов", "romanov_activity" to "код мероприятия ROM-… из ПОЛКА-ПРОЦЕССЫ-РОМАНОВ", "iso_15288" to "процесс ГОСТ ISO 15288-2023")),
        KindSpec("typical_risk", "типовой риск (библиотека)", Layer.L0, null, null, listOf("code", "statement", "cec", "category", "probability", "impact", "strategy", "measures", "applicability"), listOf("code", "statement", "cec", "category", "probability", "impact", "strategy", "measures", "applicability"), listOf(), mapOf("category" to listOf("technical", "cost", "schedule", "safety", "regulatory", "security", "programmatic"), "strategy" to listOf("mitigate", "accept", "transfer", "avoid")), listOf(), mapOf("code" to "Код", "statement" to "Формулировка", "cec" to "Условие · событие · последствие", "category" to "Категория", "probability" to "Вероятность", "impact" to "Последствия", "strategy" to "Стратегия", "measures" to "Меры", "applicability" to "Применимость"), emptyMap(), emptyMap()),
        KindSpec("stakeholder_profile", "профиль стейкхолдера (библиотека)", Layer.L0, null, null, listOf("code", "role", "name", "interests", "applicability"), listOf("code", "role", "name", "interests", "typical_needs", "applicability"), listOf(), mapOf("role" to listOf("customer", "regulator", "operator", "consumer", "supplier", "partner", "established")), listOf(), mapOf("code" to "Код", "role" to "Роль", "name" to "Наименование", "interests" to "Интересы", "typical_needs" to "Типовые нужды", "applicability" to "Применимость"), emptyMap(), emptyMap()),
        KindSpec("role", "роль", Layer.L1, null, null, listOf("code", "name", "rights"), listOf("code", "name", "rights", "phase_involvement"), listOf(), emptyMap(), listOf(), mapOf("code" to "Код", "name" to "Наименование", "rights" to "Права", "phase_involvement" to "Участие по фазам"), emptyMap(), mapOf("phase_involvement" to "роли по стадиям из phase_template.roles")),
        KindSpec("right", "право", Layer.L1, null, null, listOf("code", "description", "scope"), listOf("code", "description", "scope"), listOf(), mapOf("scope" to listOf("project", "system")), listOf(), mapOf("code" to "Код", "description" to "Описание", "scope" to "Область"), emptyMap(), emptyMap()),
        KindSpec("synthesis_run", "запуск синтеза постановки из поля", Layer.L2, "любая", "queued|running|done|error", listOf("trigger", "slice_fingerprint", "proposals", "diff", "ontology_version"), listOf("trigger", "slice_fingerprint", "slice_size", "proposals", "diff", "ontology_version", "cached", "error"), listOf(), mapOf("trigger" to listOf("manual", "new_material", "new_facts", "manual_edit")), listOf(), mapOf("trigger" to "Триггер", "slice_fingerprint" to "Отпечаток среза", "slice_size" to "Размер среза", "proposals" to "Предложения", "diff" to "Различия", "ontology_version" to "Версия онтологии", "cached" to "Из кэша", "error" to "Ошибка"), emptyMap(), mapOf("trigger" to "по команде «Сформировать постановку из поля» либо событием поля с задержкой-накоплением", "slice_fingerprint" to "отпечаток среза поля — тот же срез даёт кэш, живого вызова нет", "slice_size" to "сколько фактов и сущностей вошло в срез (потолок 50); урезание называется словами", "proposals" to "предложения понятий с происхождением n:m и рангами оснований", "diff" to "диф «поле → постановка» четырьмя группами; принятое не меняется молча", "ontology_version" to "отпечаток ОНТОЛОГИЯ-ФОРМИРОВАНИЯ.yaml — правила образования, по которым собран запуск", "cached" to "ответ взят из журнала по отпечатку среза", "error" to "причина отказа при status=error")),
        KindSpec("research_task", "исследование полноты (внешний контур)", Layer.L2, "3,4,5,7,12,точки", "formulated|launched|received|parsed", listOf("trigger_scene", "questions", "slice_fingerprint", "prompt_version", "iteration"), listOf("trigger_scene", "questions", "slice_fingerprint", "prompt_version", "iteration", "result_material", "accepted_summary"), listOf(), emptyMap(), listOf(), mapOf("trigger_scene" to "Сцена-триггер", "questions" to "Вопросы", "slice_fingerprint" to "Отпечаток среза", "prompt_version" to "Версия промпта", "iteration" to "Итерация", "result_material" to "Материал результата", "accepted_summary" to "Итог принятия"), emptyMap(), mapOf("trigger_scene" to "ровно одно из двух — сцена либо точка, откуда запущено исследование", "questions" to "вопросы из рамки и онтологии; не менее одного; инженер снимает и дописывает", "slice_fingerprint" to "срез поля, из которого собран промпт", "prompt_version" to "версия сборки промпта — по ней воспроизводится запуск", "iteration" to "номер цикла исследования по тому же месту", "result_material" to "authority=doubtful до подтверждения источников человеком", "accepted_summary" to "что принято из результата по классам")),
        KindSpec("verification_report", "верификация документа против поля", Layer.L5, "после сборки/базирования документа", "open|closed", listOf("document", "items", "at"), listOf("document", "baseline", "items", "at"), listOf(), mapOf("items.issue" to listOf("no_basis", "number_vs_fact", "contradiction", "stale")), listOf(), mapOf("document" to "Документ", "baseline" to "Базовая линия", "items" to "Элементы", "at" to "Когда"), emptyMap(), mapOf("baseline" to "снимок, против которого проверяли", "items" to "находки — тезис без основания · число против факта · противоречие · устарело; правок молча не бывает")),
        KindSpec("milestone", "программный этап / внешняя веха (из документов и плана)", Layer.L1, "2, 12, 14", "planned|passed", listOf("name", "kind", "source"), listOf("name", "kind", "date", "range", "fleet", "source", "feeds"), listOf("source"), mapOf("kind" to listOf("program_stage", "external_event", "contract")), listOf("fleet"), mapOf("name" to "Наименование", "kind" to "Вид", "date" to "Дата", "range" to "Диапазон", "fleet" to "Флот", "source" to "Источник", "feeds" to "Питает"), emptyMap(), mapOf("kind" to "вехи технологий — gate.kind=technology, не здесь", "range" to "этап записки: 0–1,5 года", "source" to "derived_from_fact", "feeds" to "что от неё зависит: даты точек, FA §4")),
        KindSpec("parse_run", "прогон разбора документа (изоляция вклада)", Layer.L2, "загрузка", "running|done|rolled_back|superseded", listOf("material", "prompt_version", "at", "facts"), listOf("material", "prompt_version", "at", "facts", "derived", "rolled_back_by"), listOf(), emptyMap(), listOf(), mapOf("material" to "Документ-источник", "prompt_version" to "Версия промпта", "at" to "Когда", "facts" to "Факты", "derived" to "Образовано", "rolled_back_by" to "Откатил"), emptyMap(), mapOf("derived" to "что образовано из его фактов")),
        KindSpec("opportunity", "возможность применения системы к чужой нужде или цели", Layer.L2, "загрузка контекстного документа, сцены 3–7", "proposed|accepted|rejected", listOf("external_item", "owner", "verdict", "rationale", "confidence"), listOf("external_item", "owner", "our_services", "verdict", "missing", "scale", "proposal", "rationale", "confidence"), listOf("external_item"), mapOf("verdict" to listOf("covered", "partial", "not_our_profile", "needs_work"), "proposal" to listOf("extend_scope", "add_service", "descope", "reject")), listOf("scale"), mapOf("external_item" to "Чужая нужда/цель", "owner" to "Владелец", "our_services" to "Наши сервисы", "verdict" to "Вердикт", "missing" to "Чего не хватает", "scale" to "Масштаб", "proposal" to "Предложение", "rationale" to "Обоснование", "confidence" to "Уверенность"), emptyMap(), mapOf("external_item" to "чужая нужда/цель с якорем", "owner" to "чья", "missing" to "чего не хватает")),
    )

    /**
     * Русские значения перечислений (`enum_labels` истины схем, 19.09).
     *
     * Ключ — «вид.поле» СЛОВАМИ ИСТИНЫ: там названы и поля-перечни
     * (`requirement.level`), и поля-ссылки в справочник
     * (`requirement.priority`), и статус записи (`requirement.status`),
     * и вердикт предложения. Экран берёт значение ТОЛЬКО отсюда:
     * «значение без метки на экране — сторож» (field_rules.enum_labels).
     */
    val enumLabels: Map<String, Map<String, String>> = mapOf(
        "baseline.kind" to mapOf("functional" to "функциональная", "allocated" to "исходные данные на проектирование", "product" to "на производство"),
        "component.nature" to mapOf("node" to "узел (железо)", "behaviour" to "поведение (ПО)"),
        "constraint.type" to mapOf("technical" to "техническое", "programmatic" to "программное", "launch" to "пусковое", "regulatory" to "регуляторное", "financial" to "финансовое"),
        "fact.disposition" to mapOf("free" to "не рассмотрен", "noted" to "учтён", "assumed" to "допущение", "adopted" to "принят", "rejected" to "отклонён", "contested" to "оспорен", "superseded" to "устарел"),
        "fact.evidence" to mapOf("claimed" to "заявлено", "corroborated" to "подтверждено", "measured" to "измерено", "assumed" to "допущение"),
        "fact.source_mark" to mapOf("И" to "внутреннее", "В" to "внешнее", "П" to "предположение"),
        "gate.expertise_answers.answer" to mapOf("yes" to "да", "no" to "нет"),
        "gate.kind" to mapOf("phase" to "точка фазы", "technology" to "веха технологии"),
        "link.type" to mapOf("owns" to "владеет", "covers" to "покрывает", "derives_from" to "выведено из", "allocated_to" to "распределено на", "satisfied_by" to "удовлетворяется", "realized_by" to "реализуется", "allocation" to "распределение", "flows_over" to "идёт по стыку", "illustrated_by" to "иллюстрируется", "traced_to" to "трассируется к", "verifies" to "верифицирует", "conflicts_with" to "противоречит", "snapshot_of" to "снимок", "input_of" to "вход для", "output_of" to "выход из", "pairs_with" to "пара к", "external_identity" to "внешняя идентичность", "deployed_on" to "развёрнуто на", "uses_item" to "использует элемент обмена", "depends_on_technology" to "зависит от технологии", "derived_from_fact" to "основание", "about" to "о", "supports" to "поддерживает", "contradicts" to "противоречит (факты)", "supersedes" to "заменяет", "confirms" to "подтверждает", "same_as" to "то же самое", "refines" to "уточняет"),
        "material.authority" to mapOf("mandatory" to "обязательный", "expert" to "экспертный", "reference" to "справочный", "doubtful" to "сомнительный"),
        "material.role" to mapOf("charter" to "устав", "tor" to "источник требований", "regulatory" to "норматив", "context" to "обстановка", "supplier" to "поставщик", "heritage" to "наследие"),
        "need.coverage_expected" to mapOf("service" to "сервисом", "constraint" to "ограничением", "programme" to "программой", "requirement" to "требованием"),
        "opportunity.verdict" to mapOf("covered" to "закрываем", "partial" to "частично", "not_our_profile" to "не наш профиль", "needs_work" to "нужна доработка"),
        "parameter.maturity_class" to mapOf("estimated" to "оценка", "modified" to "модификация", "off_the_shelf" to "серийное", "measured" to "измерено"),
        "project.standard" to mapOf("NASA-7120" to "NASA (NPR 7120.5)"),
        "proposal.decision" to mapOf("pending" to "ждёт", "accepted" to "принято", "rejected" to "отклонено", "deferred" to "отложено"),
        "proposal.verdict" to mapOf("new" to "новое", "augment" to "дополнить", "contradict" to "противоречие", "confirm" to "подтверждение"),
        "requirement.category" to mapOf("functional" to "функциональное", "performance" to "характеристика", "interface" to "интерфейсное", "operational" to "эксплуатационное", "constraint" to "ограничение", "safety" to "безопасность", "environment" to "среда", "regulatory" to "регуляторное", "security" to "защита информации", "data" to "данные"),
        "requirement.ears_pattern" to mapOf("ubiquitous" to "всегда", "event" to "по событию", "state" to "в состоянии", "unwanted" to "нежелательное", "optional" to "опциональное"),
        "requirement.level" to mapOf("project" to "проектное", "scenario" to "сценарное", "system" to "системное", "subsystem" to "подсистемное", "interface" to "интерфейсное"),
        "requirement.priority" to mapOf("high" to "высокий", "medium" to "средний", "low" to "низкий"),
        "requirement.status" to mapOf("Draft" to "черновик", "Preliminary" to "предварительное", "Approved" to "утверждено", "Baseline" to "базировано", "Cancelled" to "отменено"),
        "risk.category" to mapOf("technical" to "техническая", "cost" to "стоимость", "schedule" to "сроки", "safety" to "безопасность", "regulatory" to "регуляторный", "security" to "защита", "programmatic" to "программный"),
        "risk.strategy" to mapOf("mitigate" to "снизить", "accept" to "принять", "transfer" to "передать", "avoid" to "избежать"),
        "stakeholder.attitude" to mapOf("supports" to "поддерживает", "neutral" to "нейтрален", "resists" to "сопротивляется"),
        "stakeholder.influence" to mapOf("decides" to "решает", "influences" to "влияет", "informed" to "информируется"),
        "stakeholder.role" to mapOf("customer" to "заказчик", "regulator" to "регулятор", "operator" to "оператор", "consumer" to "потребитель", "supplier" to "поставщик", "partner" to "партнёр", "established" to "учреждаемый"),
        "state_machine.states.kind" to mapOf("mode" to "режим", "state" to "состояние"),
        "state_machine.transitions.trigger" to mapOf("exchange" to "обмен", "event" to "событие", "timer" to "таймер"),
    )

    /**
     * Операторы величины: код записи → знак для экрана. Схема знает
     * только эти коды («>=»), а человек читает знак («≥»).
     */
    val measureOps: Map<String, String> = mapOf(
        "=" to "=",
        ">=" to "≥",
        "<=" to "≤",
        ">" to ">",
        "<" to "<",
        "~" to "≈",
    )

    val byCode: Map<String, KindSpec> = all.associateBy { it.code }

    /** Вид вне перечня не существует: отказ вместо тихого пропуска. */
    fun of(code: String): KindSpec = byCode[code]
        ?: error("вид «$code» не описан в СХЕМЫ-ПОЛЕЙ-V2.yaml — вид вне истины схем не существует")
}
